export const SET_CURRENT_USER = 'chat/SET_CURRENT_USER';
export const SET_CURRENT_ROOM = 'chat/SET_CURRENT_ROOM';

export const ADD_NEW_ROOM = 'chat/ADD_NEW_ROOM';

export const PUSH_NEW_MESSAGE = 'chat/PUSH_NEW_MESSAGE';

export const USER_JOINED_ROOM = 'chat/USER_JOINED_ROOM';
export const USER_LEFT_ROOM = 'chat/USER_LEFT_ROOM';

export const ROOM_DELETED = 'chat/ROOM_DELETED';
export const MESSAGE_DELETED = 'chat/MESSAGE_DELETED';
export const MESSAGE_EDITED = 'chat/MESSAGE_EDITED';

export const USER_HAS_BEEN_CHANGED = 'chat/USER_HAS_BEEN_CHANGED';

export const GET_ROOMS_REQUEST = 'chat/GET_ROOMS_REQUEST';
export const GET_ROOMS_SUCCESS = 'chat/GET_ROOMS_SUCCESS';
export const GET_ROOMS_FAILURE = 'chat/GET_ROOMS_FAILURE';

export const UPDATE_PROFILE_REQUEST = 'chat/UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'chat/UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'chat/UPDATE_PROFILE_FAILURE';

export const SAVE_NEW_AVATAR = 'chat/SAVE_NEW_AVATAR';
